<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-windows10.0.19041.0</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <LangVersion>preview</LangVersion>
    <SingleProject>true</SingleProject>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ApplicationTitle>PaycheckCalc</ApplicationTitle>
    <ApplicationId>com.erik.paycheckcalc</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
	<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#424242" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\ok_ow2_2026_percentage.json" LogicalName="ok_ow2_2026_percentage.json" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\us_irs_15t_2026_percentage_automated.json" LogicalName="us_irs_15t_2026_percentage_automated.json" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\ca_method_b_2026.json" LogicalName="ca_method_b_2026.json" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\ar_withholding_2026.json" LogicalName="ar_withholding_2026.json" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\co_dr0004_2026.json" LogicalName="co_dr0004_2026.json" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\connecticut_withholding_2026.json" LogicalName="connecticut_withholding_2026.json" />
	<MauiAsset Include="..\PaycheckCalc.Core\Data\Schemas\*.json" LogicalName="schemas\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9" />
	<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.70" />
	<PackageReference Include="Microsoft.Maui.Graphics.Skia" Version="10.0.70" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaycheckCalc.Core\PaycheckCalc.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Images\" />
  </ItemGroup>

</Project>
